### ISSUE TITLE
Customer Billing (MEGH-5461)

### ISSUE THREAD

**Issue by jetpax** [espressif/esp-rainmaker#308]
### Answers checklist.

- [X] I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.
- [X] I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.
- [X] I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.

### General issue report

Lets say I use the Rainmaker service for a product and pay the AWS & ESP charges, and the product has 10,000 individual users.

What is the recommended mechanism for passing this through to my users?

ie how does customer billing work?

**Comment by shahpiyushv** [comment]
ESP RainMaker private deployments do not explicitly have any end customer billing as it could be very much use case specific. Some customers may want to have a flat monthly billing, some may chose billing linked to device count, others may link to the messaging count. You can pull out such info from your private RainMaker deployment and charge the end users accordingly. 

Since this is linked to business aspect, please also reach out to our sales team at sales@espressif.com or the RainMaker admin at esp-rainmaker-admin@espressif.com
