### ISSUE TITLE
Dashboard: Cannot delete OTA job once triggered (MEGH-2079)

### ISSUE THREAD

**Issue by JohnMacrae** [espressif/esp-rainmaker#66]
Is there a method to do this? Otherwise failed tests just leave a large list of unfulfilled jobs.

Thanks

**Comment by shahpiyushv** [comment]
@JohnMacrae , this is actually on purpose, so that historical data does not get deleted inadvertently. However, we could still add an option to first "archive" a job and then allow deleting only archived jobs. This will help have a clean view of the jobs table, yet address the original problem I mentioned. We will take this up as an enhancement in future,

**Comment by JohnMacrae** [comment]
Thanks @shahpiyushv :)

**Comment by CodorStelian** [comment]
Also, a clear option for all node logs like errors should be implemented. Is annoying to see hundreds of errors from previous versions.
Thanks

**Comment by shahpiyushv** [comment]
@CodorStelian , Noted!

**Comment by shahpiyushv** [comment]
@JohnMacrae . closing this issue since the RainMaker dashboard now gives an option to archive OTA jobs. Please have a look.
