### ISSUE TITLE
unable to find fan device when searching through Google Home (MEGH-2892)

### ISSUE THREAD

**Issue by rajeshris** [espressif/esp-rainmaker#97]
We built the APK from current source and the standalone esp-rainmaker app was successfully tested for fan support (on, off,speed).We set up the Alexa app to communicate with the fan through Rainmaker and control the fan operations. 

However, While setting the Google home App , I am unable to find a "fan" device after linking to my esp-rainmaker account .

There was a thread on the forum and it said the support was added ,however am running into same issues as reported in the thread .
https://esp32.com/viewtopic.php?f=41&t=23396&sid=1d8ad5184d0d7a587f510e26083c02fc

**Comment by shahpiyushv** [comment]
@rajeshris Transferred the issue here since it is not specific to the Android app. After checking internally , I found out that the fan support wasn't pushed out to production because the [fan speed control from GVA](https://developers.google.com/assistant/smarthome/traits/fanspeed) was not as straightforward as a range controller for Alexa. We will check how this can be supported and add it asap.

**Comment by shahpiyushv** [comment]
@rajeshris , forgot to mention here, but support for Fan was added in GVA some time back. Please check. Closing this issue now.

**Comment by maxakash** [comment]
> @rajeshris , forgot to mention here, but support for Fan was added in GVA some time back. Please check. Closing this issue now.

Please add support for Blinds in GVA.
